server:
  port: 8991

spring:
  application:
    name: empserver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: empserver
    loadbalancer:
      retry:
        enabled: false
  redis:
    port: 6379
    host: 8.140.153.233
  datasource:
    username: root
    password: 1178055813
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.lbh.entity
  mapper-locations: classpath:mapper/*.xml