server:
  port: 8990

spring:
  application:
    name: fileserver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: fileserver
    loadbalancer:
      retry:
        enabled: false
  redis:
    port: 6379
    host: 8.140.153.233
  resources:
    static-locations: file:${upload.dir}
upload.dir: /Users/刘斌豪/IdeaProjects/ems-parent/ems-fileserver/src/main/resources/photo
